export function getAiFacts() {
  return [
    "AI's concept dates back to ancient myths like Talos.",
    "The first AI program, Logic Theorist, was created in 1956.",
    "The term 'Artificial Intelligence' was coined at the Dartmouth Conference.",
    "Early AI research focused on chess and checkers.",
    "AI funding dried up in the 1970s during the 'AI Winter.'",
    "The 1997 victory of IBM's Deep Blue over Garry Kasparov marked AI's rise in chess.",
    "Neural networks were revived in the 1990s after being overshadowed by expert systems.",
    "AlphaGo’s 2016 win in Go was a major reinforcement learning milestone.",
    "The Perceptron, the first neural network, was built in 1958.",
    "The 2017 Transformer model revolutionized natural language processing.",
    "Neural networks can approximate any function (Universal Approximation Theorem).",
    "Symbolic AI dominated before the rise of machine learning.",
    "AI uses gradient descent to 'learn.'",
    "AI can't solve all problems; 'No Free Lunch' theorem proves this.",
    "Reinforcement learning is based on reward optimization.",
    "Transfer learning allows AI to reuse knowledge across tasks.",
    "AI struggles with 'catastrophic forgetting' in sequential tasks.",
    "Scaling laws predict improvements with larger models and data.",
    "The 'alignment problem' deals with AI following human values.",
    "Explainable AI (XAI) focuses on making decisions interpretable.",
    "GPT models have billions of parameters.",
    "Transformers process data in parallel, unlike older RNNs.",
    "Few-shot learning allows AI to generalize from few examples.",
    "AI models can 'hallucinate' false information.",
    "Large language models like GPT exhibit emergent behaviors.",
    "Self-supervised learning trains AI on unlabeled data.",
    "Adversarial attacks fool AI with minimal data changes.",
    "Neural networks require extensive computation and energy.",
    "Sparse neural networks aim to reduce computational costs.",
    "Federated learning trains AI on decentralized data.",
    "AI struggles with common-sense reasoning.",
    "Ethical biases in AI mirror societal inequalities.",
    "AI systems cannot understand; they only simulate intelligence.",
    "Current AI lacks true creativity.",
    "The black box problem complicates trust in AI systems.",
    "General AI (AGI) remains a distant goal.",
    "AI often overfits data, harming real-world accuracy.",
    "Reinforcement learning struggles with sparse rewards.",
    "AI efficiency lags far behind the human brain.",
    "AI models require massive amounts of labeled training data.",
    "Turing proposed the Turing Test to measure AI intelligence.",
    "The Chinese Room argument questions AI's ability to truly 'understand.'",
    "AI consciousness remains speculative.",
    "Superintelligence could pose existential risks.",
    "Isaac Asimov’s 'Three Laws of Robotics' inspired AI ethics.",
    "The 'paperclip maximizer' illustrates risks of misaligned goals.",
    "AI doesn’t know when it’s wrong.",
    "The singularity predicts AI surpassing human intelligence.",
    "Philosophers debate whether AI can have free will.",
    "Neuromorphic computing mimics the brain's efficiency.",
    "DALL-E generates images from text descriptions.",
    "AI can optimize hardware designs using reinforcement learning.",
    "Multimodal AI integrates text, images, and sound.",
    "AlphaFold predicts protein structures.",
    "AI systems like DeepMind use advanced reinforcement learning.",
    "Large AI models consume significant energy to train.",
    "Models like GPT use unsupervised pretraining.",
    "OpenAI’s safety team researches AI alignment.",
    "Quantum computing could accelerate AI training.",
    "GPT's output depends heavily on prompt phrasing.",
    "AI is critical in identifying unknown exoplanets.",
    "AI powers generative models that simulate human creativity.",
    "Bayesian networks model AI’s probabilistic reasoning.",
    "AI's explainability determines adoption in sensitive fields.",
    "Transfer learning enhances AI with minimal new data.",
    "Multi-agent systems simulate collaborative AI behaviors.",
    "Meta-learning enables AI to 'learn how to learn.'",
    "Hybrid AI merges symbolic and neural methods.",
    "Evolutionary algorithms simulate natural selection.",
    "Sparse models aim for efficiency by ignoring redundant parameters.",
    "Self-improving AI may eventually optimize its own architecture.",
    "Neural architecture search automates the design of better AI models.",
    "AI’s emergent abilities were not explicitly programmed.",
    "Deep learning draws parallels to biological vision.",
    "AI systems outperform humans in narrow tasks but fail in general reasoning.",
    "Reinforcement learning models play games better than human players.",
    "Current AI cannot handle true uncertainty well.",
    "AI remains poor at tasks requiring physical interaction.",
    "Neural nets cannot yet reason causally like humans.",
    "The brain vastly outperforms AI in energy efficiency.",
    "The AI ethics debate began in the 20th century.",
    "Bias in AI comes from biased datasets, not algorithms themselves.",
    "AI’s rapid progress may outpace regulation.",
    "Autonomous weapons are a major ethical concern.",
    "Ethical AI aligns its actions with human moral principles.",
    "Privacy concerns arise with AI surveillance systems.",
    "Transparency in AI remains a critical challenge.",
    "AI decisions can unintentionally harm marginalized groups.",
    "The alignment problem is unsolved for superintelligent AI.",
    "'Friendly AI' is a term for AI designed to benefit humanity.",
    "Early AI overestimated the ease of replicating human reasoning.",
    "Neural networks were inspired by the brain but work differently.",
    "AI models don’t 'think'; they find patterns in data.",
    "General AI would need to understand abstract reasoning.",
    "Most AI research is concentrated in a few global tech hubs.",
    "AI winter refers to funding cuts due to unmet expectations.",
    "AI depends heavily on advancements in hardware, especially GPUs.",
    "The scaling hypothesis suggests bigger AI models lead to better results.",
    "Recursive AI could lead to exponential advancements.",
    "Despite its power, AI still lacks true intuition.",
  ];
}
