export function getAnimalFacts() {
  return [
    "A group of flamingos is called a 'flamboyance.'",
    "Cows have best friends and can get stressed when they are separated.",
    "Octopuses have three hearts and blue blood.",
    "Elephants are the only mammals that can't jump.",
    "Sloths can hold their breath longer than dolphins (up to 40 minutes).",
    "A group of owls is called a 'parliament.'",
    "The fingerprints of a koala are so indistinguishable from humans that they have confused crime scene investigators.",
    "A shrimp's heart is located in its head.",
    "Seahorses mate for life, and males carry the babies.",
    "Giraffes only need 5-30 minutes of sleep per day.",
    "Penguins propose to their mates with a pebble.",
    "The slowest fish is the dwarf seahorse, moving at 5 feet per hour.",
    "Cats have 32 muscles in each ear.",
    "A group of porcupines is called a 'prickle.'",
    "Dolphins have unique names for each other using specific whistles.",
    "Frogs can throw up their stomachs to clean them.",
    "Starfish don’t have brains or blood.",
    "Some turtles can breathe through their butts.",
    "Butterflies can taste with their feet.",
    "Female lions do 90% of the hunting in their pride.",
    "Honey never spoils—archaeologists have found edible honey in ancient Egyptian tombs.",
    "Dogs' noses are wet to help absorb scent chemicals.",
    "Axolotls can regenerate entire limbs and even parts of their hearts and brains.",
    "Crocodiles can't stick out their tongues.",
    "Male peacocks are called 'peafowls,' while the females are 'peahens.'",
    "A group of crows is called a 'murder.'",
    "A newborn kangaroo is the size of a lima bean.",
    "Sea otters hold hands while they sleep to keep from drifting apart.",
    "A cheetah can accelerate faster than most sports cars.",
    "A group of frogs is called an 'army.'",
    "The blue whale’s heart is the size of a small car.",
    "Hummingbirds are the only birds that can fly backward.",
    "Wombat poop is cube-shaped.",
    "Male seahorses give birth to their young.",
    "Snakes can sense earthquakes days before they happen.",
    "Cats can make over 100 different sounds, while dogs can only make about 10.",
    "A group of jellyfish is called a 'smack.'",
    "The world's smallest mammal is the bumblebee bat.",
    "The largest jellyfish, the lion’s mane jellyfish, can have tentacles over 120 feet long.",
    "Rats and mice laugh when tickled.",
    "Polar bears have black skin underneath their white fur.",
    "An octopus can taste with its tentacles.",
    "A group of ravens is called an 'unkindness.'",
    "Sharks existed before trees did.",
    "Camels store fat, not water, in their humps.",
    "Cows can walk upstairs, but not downstairs.",
    "There are more chickens on Earth than humans.",
    "A tarantula can live for over 20 years.",
    "Rabbits can’t vomit.",
    "The heart of a shrimp is in its head.",
    "Ostriches can run faster than horses.",
    "A group of bats is called a 'cauldron.'",
    "An ant can lift 50 times its body weight.",
    "Spiders recycle their webs by eating them.",
    "Koalas sleep up to 22 hours a day.",
    "The platypus doesn’t have a stomach.",
    "Owls are the only birds that can see the color blue.",
    "Lobsters can live for over 100 years.",
    "Male penguins gift their mates with the smoothest pebble they can find.",
    "Goldfish can recognize their owners.",
    "Baby elephants suck their trunks for comfort.",
    "A group of ferrets is called a 'business.'",
    "The mantis shrimp can punch with the force of a bullet.",
    "Blue whales can consume up to 4 tons of krill a day.",
    "Horses can sleep standing up.",
    "Kangaroos can’t walk backward.",
    "Some fish can recognize themselves in a mirror.",
    "A group of cats is called a 'clowder.'",
    "Bees can fly higher than Mount Everest.",
    "Ants never sleep.",
    "Alpacas hum when they are curious or stressed.",
    "Flamingos are naturally white; their diet of brine shrimp and algae turns them pink.",
    "The horn of a rhinoceros is made of keratin, the same material as human nails.",
    "The fingerprints of a koala are almost indistinguishable from humans.",
    "Baby goats (kids) have accents.",
    "Crocodiles can live up to 70 years.",
    "Snails can sleep for up to three years.",
    "The heaviest insect is the Goliath beetle, weighing up to 3.5 ounces.",
    "Dolphins sleep with one eye open.",
    "Woodpeckers can peck 20 times per second.",
    "Sheep can recognize the faces of at least 50 other sheep and humans.",
    "A jellyfish is 95% water.",
    "Gorillas can catch human colds.",
    "Dragonflies have been around for over 300 million years.",
    "Some species of frogs can freeze solid and survive.",
    "A group of rhinos is called a 'crash.'",
    "The common garden worm has five pairs of hearts.",
    "Chameleons can move their eyes in two different directions at once.",
    "The pistol shrimp creates a bubble strong enough to stun prey with sound.",
    "Sharks can go into a trance by flipping them upside down.",
    "A dog's sense of smell is 40 times stronger than a human's.",
    "Pigeons can recognize themselves in mirrors.",
    "Male lyrebirds can mimic chainsaws and camera shutters.",
    "Some moths don't have mouths and live only to reproduce.",
    "Cats spend 70% of their lives sleeping.",
    "Flamingos bend their legs at the ankle, not the knee.",
    "The Arctic tern migrates 25,000 miles each year.",
    "The eyes of an ostrich are bigger than its brain.",
    "The smallest dog breed, the Chihuahua, can live up to 20 years.",
    "Barn owls have asymmetrical ears to help them locate prey.",
  ];
}
