import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import HomeAnimations from "../src/js/main";
import Link from "next/link";
// export const getServerSideProps = async () => {};
export default function Home({ title, content }) {
  // const eggos = "eggos";

  return (
    <div>
      <Head>
        <title>Marvin Intelligence</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <>
          <meta charSet="utf-8" />
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {/* <title>Solid Template</title> */}
          <link
            href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans:400,600"
            rel="stylesheet"
          />
          {/* <Script src="../src/js/main.js"></Script> */}
          {/* /Users/fromastermarv/Documents/Codeyard/marvinfo/src/js/main.js */}
          {/* <link rel="stylesheet" href="dist/css/style.css" /> */}
        </>
      </Head>
      <HomeAnimations />
      <div className="is-boxed has-animations">
        <div className="body-wrap">
          <header className="site-header">
            <div className="container">
              <div className="site-header-inner">
                <div className="brand header-brand">
                  <h1 className="m-0">
                    <img
                      // className="header-logo-image"
                      src="logo.png"
                      alt="Logo"
                      width={200}
                    />
                  </h1>
                </div>
              </div>
            </div>
          </header>
          <main>
            <section className="hero">
              <div className="container">
                <div className="hero-inner">
                  <div className="hero-copy">
                    <h1 className="hero-title mt-0">
                      Unlock the Power of Automated Learning
                    </h1>
                    <p className="hero-paragraph">
                      Empower your intellectual journey with your personal team
                      of AI researchers. Discover, Learn, and Master any subject
                      matter effortlessly.
                    </p>
                    <div className="hero-cta">
                      <Link
                        className="button button-primary"
                        href="/account/log-in"
                      >
                        Start your Free Trial
                      </Link>
                      <a className="button" href="#">
                        Meet your AI Team
                      </a>
                    </div>
                  </div>
                  <div className="hero-figure anime-element">
                    <svg
                      className="placeholder"
                      width={528}
                      height={396}
                      viewBox="0 0 528 396"
                    >
                      <rect
                        width={528}
                        height={396}
                        style={{ fill: "transparent" }}
                      />
                    </svg>
                    <div
                      className="hero-figure-box hero-figure-box-01"
                      data-rotation="45deg"
                    />
                    <div
                      className="hero-figure-box hero-figure-box-02"
                      data-rotation="-45deg"
                    />
                    <div
                      className="hero-figure-box hero-figure-box-03"
                      data-rotation="0deg"
                    />
                    <div
                      className="hero-figure-box hero-figure-box-04"
                      data-rotation="-135deg"
                    />
                    <div className="hero-figure-box hero-figure-box-05" />
                    <div className="hero-figure-box hero-figure-box-06" />
                    <div className="hero-figure-box hero-figure-box-07" />
                    <div
                      className="hero-figure-box hero-figure-box-08"
                      data-rotation="-22deg"
                    />
                    <div
                      className="hero-figure-box hero-figure-box-09"
                      data-rotation="-52deg"
                    />
                    <div
                      className="hero-figure-box hero-figure-box-10"
                      data-rotation="-50deg"
                    />
                  </div>
                </div>
              </div>
            </section>
            <section className="features section">
              <div className="container">
                <div className="features-inner section-inner has-bottom-divider">
                  <div className="features-wrap">
                    <div className="feature text-center is-revealing">
                      <div className="feature-inner">
                        <div className="feature-icon">
                          <img
                            style={{
                              height: "380px",
                              objectFit: "cover",
                            }}
                            src="splash-steps/sign-up.png"
                            alt="Feature 01"
                          />
                        </div>
                        <h4 className="feature-title mt-24">
                          Step 1 - Sign Up
                        </h4>
                        <p className="text-sm mb-0">
                          Sign up and name your Intelligence Agency
                        </p>
                      </div>
                    </div>
                    <div className="feature text-center is-revealing">
                      <div className="feature-inner">
                        <div className="feature-icon">
                          <img
                            style={{
                              height: "380px",
                              objectFit: "cover",
                            }}
                            src="splash-steps/hire-agent.png"
                            alt="Feature 02"
                          />
                        </div>
                        <h4 className="feature-title mt-24">
                          Step 2 - Hire Your Agents
                        </h4>
                        <p className="text-sm mb-0">
                          Hire your first AI Agent and assign a domain of
                          expertise
                        </p>
                      </div>
                    </div>
                    <div className="feature text-center is-revealing">
                      <div className="feature-inner">
                        <div className="feature-icon">
                          <img
                            style={{
                              height: "380px",
                              objectFit: "cover",
                            }}
                            src="splash-steps/assign-mission.png"
                            alt="Feature 03"
                          />
                        </div>
                        <h4 className="feature-title mt-24">
                          Step 3 - Assign Missions
                        </h4>
                        <p className="text-sm mb-0">
                          Assign your first mission. Let your agent explore the
                          depths of any topic
                        </p>
                      </div>
                    </div>
                    <div className="feature text-center is-revealing">
                      <div className="feature-inner">
                        <div className="feature-icon">
                          <img
                            src="splash-steps/review-reports.png"
                            alt="Feature 04"
                            style={{
                              height: "380px",
                              objectFit: "cover",
                            }}
                          />
                        </div>
                        <h4 className="feature-title mt-24">
                          Step 4 - Review Reports:{" "}
                        </h4>
                        <p className="text-sm mb-0">
                          Receive comprehensive reports from your agents
                        </p>
                      </div>
                    </div>
                    <div className="feature text-center is-revealing">
                      <div className="feature-inner">
                        <div className="feature-icon">
                          <img
                            src="splash-steps/iterative.png"
                            alt="Feature 05"
                            style={{
                              height: "380px",
                              objectFit: "cover",
                            }}
                          />
                        </div>
                        <h4 className="feature-title mt-24">
                          Step 5 - Iterative Learning:
                        </h4>
                        <p className="text-sm mb-0">
                          Continue the process. Iterate and learn from the
                          reports
                        </p>
                      </div>
                    </div>
                    <div className="feature text-center is-revealing">
                      <div className="feature-inner">
                        <div className="feature-icon">
                          <img
                            src="splash-steps/get-started.png"
                            alt="Feature 06"
                            style={{
                              height: "380px",
                              objectFit: "cover",
                            }}
                          />
                        </div>
                        <h4 className="feature-title mt-24">Get Started</h4>
                        <p className="text-sm mb-0">
                          <Link href="/account/log-in">
                            Start your Free Trial Now
                          </Link>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <section className="pricing section">
              <div className="container-sm">
                <div className="pricing-inner section-inner">
                  <div className="pricing-header text-center">
                    <h2 className="section-title mt-0">
                      Free Trial Offer - Explore the World of Knowledge with Us!
                    </h2>
                    <p className="section-paragraph mb-0 text-white">
                      <div>
                        <p>
                          At Intelligence.Marvin.Technology, we believe in the
                          transformative power of knowledge. "But don't just
                          take my word for it,"
                          <a
                            target="_blank"
                            rel="noopener noreferrer"
                            href="https://www.readingrainbow.org/"
                          >
                            (LeVar Burton Reading Rainbow voice)
                          </a>
                          . We want you to experience it firsthand, which is why
                          we're offering you a risk-free trial of our service.
                        </p>
                        <p>
                          Our free trial gives you access to the full
                          Intelligence.Marvin.Technology experience, allowing
                          you to create your first 100 missions absolutely free
                          or for 14 days, whichever comes first.
                        </p>
                        <p>
                          During your trial period, you'll have the opportunity
                          to explore and utilize all our platform's
                          capabilities, from managing your own team of agents to
                          receiving comprehensive and curated reports. With our
                          intuitive dashboard and innovative autonomous
                          missions, you'll discover a new, engaging way to learn
                          and process information.
                        </p>
                        <p>
                          And the best part? No commitment. If you feel
                          Intelligence.Marvin.Technology isn't the right fit for
                          you, you can cancel anytime during the trial period at
                          no cost. So why wait? Begin your knowledge exploration
                          journey today!
                        </p>
                        <p>
                          *Please note: After the free trial, your plan will
                          automatically convert into a paid subscription unless
                          cancelled. Details of our subscription plans can be
                          found below.
                        </p>
                      </div>
                    </p>
                  </div>
                  <div className="pricing-tables-wrap">
                    <h2>Basic Plan</h2>
                  </div>
                  <div className="pricing-tables-wrap">
                    <div className="pricing-table">
                      <div className="pricing-table-inner is-revealing">
                        <div className="pricing-table-main">
                          <div className="pricing-table-header pb-24">
                            <div className="pricing-table-price">
                              <span className="pricing-table-price-currency h2">
                                $
                              </span>
                              <span className="pricing-table-price-amount h1">
                                10
                              </span>
                              <span className="text-xs">/month</span>
                            </div>
                          </div>
                          <div className="pricing-table-features-title text-xs pt-24 pb-24">
                            What you will get
                          </div>
                          <ul className="pricing-table-features list-reset text-xs">
                            <li>
                              <span>500 Missions</span>
                            </li>
                            <li>
                              <span>Up to 5 Agents</span>
                            </li>
                            <li>
                              <span>Unlimited Report Storage</span>
                            </li>
                            <li>
                              <span>Personal Customer Service</span>
                            </li>
                          </ul>
                        </div>
                        <div className="pricing-table-cta mb-8">
                          <a
                            className="button button-primary button-shadow button-block"
                            href="#"
                          >
                            Pre order now
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="pricing-tables-wrap">
                    <h2>Pro Plan</h2>
                  </div>
                  <div className="pricing-tables-wrap">
                    <div className="pricing-table">
                      <div className="pricing-table-inner is-revealing">
                        <div className="pricing-table-main">
                          <div className="pricing-table-header pb-24">
                            <div className="pricing-table-price">
                              <span className="pricing-table-price-currency h2">
                                $
                              </span>
                              <span className="pricing-table-price-amount h1">
                                20
                              </span>
                              <span className="text-xs">/month</span>
                            </div>
                          </div>
                          <div className="pricing-table-features-title text-xs pt-24 pb-24">
                            What you will get
                          </div>
                          <ul className="pricing-table-features list-reset text-xs">
                            <li>
                              <span>2000 Missions</span>
                            </li>
                            <li>
                              <span>Unlimited Agents</span>
                            </li>
                            <li>
                              <span>Automated Missions</span>
                            </li>
                            <li>
                              <span>Personal Customer Service</span>
                            </li>
                          </ul>
                        </div>
                        <div className="pricing-table-cta mb-8">
                          <a
                            className="button button-primary button-shadow button-block"
                            href="#"
                          >
                            Pre order now
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="pricing-tables-wrap">
                    <h2>Enterprise</h2>
                  </div>
                  <div className="pricing-tables-wrap">
                    <div className="pricing-table">
                      <div className="pricing-table-inner is-revealing">
                        <div className="pricing-table-main">
                          <div className="pricing-table-header pb-24">
                            <div className="pricing-table-price">
                              Custom Pricing
                              {/* <span className="pricing-table-price-currency h2">
                                $
                              </span> */}
                              {/* <span className="pricing-table-price-amount h1">
                                Custom Pricing
                              </span> */}
                              {/* <span className="text-xs">/month</span> */}
                            </div>
                          </div>
                          <div className="pricing-table-features-title text-xs pt-24 pb-24">
                            What you will get
                          </div>
                          <ul className="pricing-table-features list-reset text-xs">
                            {/* higher level of service, more API calls, priority support, and possible API integrations */}
                            <li>
                              <span>More API calls</span>
                            </li>
                            <li>
                              <span>Automated Missions</span>
                            </li>
                            <li>
                              <span>Possible API integrations</span>
                            </li>
                            <li>
                              <span>Priority support</span>
                            </li>
                          </ul>
                        </div>
                        <div className="pricing-table-cta mb-8">
                          <a
                            className="button button-primary button-shadow button-block"
                            href="#"
                          >
                            Pre order now
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <section className="cta section">
              <div className="container">
                <div className="cta-inner section-inner">
                  <h3 className="section-title mt-0">
                    Want to talk to a human about it?
                  </h3>
                  <div className="cta-cta">
                    <a
                      className="button button-primary button-wide-mobile"
                      href="#"
                    >
                      Get in touch
                    </a>
                  </div>
                </div>
              </div>
            </section>
          </main>
          <footer className="site-footer">
            <div className="container">
              <div className="site-footer-inner">
                <div className="brand footer-brand">
                  <a href="#">
                    <img
                      className="header-logo-image"
                      src="logo.png"
                      alt="Logo"
                      width={200}
                    />
                  </a>
                </div>
                <ul className="footer-links list-reset">
                  <li>
                    <a href="#">Contact</a>
                  </li>
                  <li>
                    <a href="#">About us</a>
                  </li>
                  <li>
                    <a href="#">FAQ's</a>
                  </li>
                  <li>
                    <a href="#">Support</a>
                  </li>
                </ul>
                {/* <ul className="footer-social-links list-reset">
                  <li>
                    <a href="#">
                      <span className="screen-reader-text">Facebook</span>
                      <svg
                        width={16}
                        height={16}
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M6.023 16L6 9H3V6h3V4c0-2.7 1.672-4 4.08-4 1.153 0 2.144.086 2.433.124v2.821h-1.67c-1.31 0-1.563.623-1.563 1.536V6H13l-1 3H9.28v7H6.023z"
                          fill="#0270D7"
                        />
                      </svg>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <span className="screen-reader-text">Twitter</span>
                      <svg
                        width={16}
                        height={16}
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M16 3c-.6.3-1.2.4-1.9.5.7-.4 1.2-1 1.4-1.8-.6.4-1.3.6-2.1.8-.6-.6-1.5-1-2.4-1-1.7 0-3.2 1.5-3.2 3.3 0 .3 0 .5.1.7-2.7-.1-5.2-1.4-6.8-3.4-.3.5-.4 1-.4 1.7 0 1.1.6 2.1 1.5 2.7-.5 0-1-.2-1.5-.4C.7 7.7 1.8 9 3.3 9.3c-.3.1-.6.1-.9.1-.2 0-.4 0-.6-.1.4 1.3 1.6 2.3 3.1 2.3-1.1.9-2.5 1.4-4.1 1.4H0c1.5.9 3.2 1.5 5 1.5 6 0 9.3-5 9.3-9.3v-.4C15 4.3 15.6 3.7 16 3z"
                          fill="#0270D7"
                        />
                      </svg>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <span className="screen-reader-text">Google</span>
                      <svg
                        width={16}
                        height={16}
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M7.9 7v2.4H12c-.2 1-1.2 3-4 3-2.4 0-4.3-2-4.3-4.4 0-2.4 2-4.4 4.3-4.4 1.4 0 2.3.6 2.8 1.1l1.9-1.8C11.5 1.7 9.9 1 8 1 4.1 1 1 4.1 1 8s3.1 7 7 7c4 0 6.7-2.8 6.7-6.8 0-.5 0-.8-.1-1.2H7.9z"
                          fill="#0270D7"
                        />
                      </svg>
                    </a>
                  </li>
                </ul> */}
                <div className="footer-copyright">
                  © 2023 Marvin.Technology, all rights reserved
                </div>
              </div>
            </div>
          </footer>
        </div>

        {/* <MyComponent title={title} content={content} /> */}
        {/* <div>Start My Free Trial</div>
      <div>Log In</div> */}
        {/* <div className="brand header-brand">
        <h1 className="m-0">
          <a href="#">
            <Image
              className="header-logo-image"
              src="dist/images/logo.svg"
              alt="Logo"
            />
          </a>
        </h1>
      </div> */}
      </div>
    </div>
  );
}

// page 2 content:
