const areas = [
  "Cooking",
  "Programming",
  "Scriptwriting",
  "Business Planning",
  "Research",
  "Education",
  "Health and Fitness",
  "Music",
  "Art",
  "Gaming",
  "Translation",
  "Mental Health",
  "Medicine",
  "Data Analysis",
  "Agriculture",
  "Manufacturing",
  "Marketing",
  "Sales",
  "Finance",
  "Human Resources",
  "Cybersecurity",
  "E-commerce",
  "Home Automation",
  "Elderly Care",
  "Environment",
  "Autonomous Vehicles",
  "Personal Assistants",
  "News and Publishing",
  "Weather Forecasting",
  "Robotics",
  "Legal",
  "Real Estate",
  "Travel",
  "Space Exploration",
  "Fashion",
  "Literature",
  "Comedy",
  "Sports",
  "Politics",
  "Urban Planning",
  "Event Planning",
  "Career Counseling",
  "Archaeology",
  "Linguistics",
  "Philosophy",
  "Cosmetology",
  "Genetics",
  "Photography",
  "Wildlife",
  "Construction",
  "Aviation",
  "Astrophysics",
  "Customer Service",
  "Journalism",
  "Ethical Decision Making",
  "Animation",
  "Shopping",
  "Podcasting",
  "Screenwriting",
  "Time Management",
  "Civil Engineering",
  "Film Editing",
  "Meteorology",
  "Graphic Design",
  "Content Moderation",
  "Handwriting Recognition",
  "Pet Care",
  "Social Media",
  "Landscape Design",
  "Architecture",
  "Brewing",
  "Gambling",
  "Acting",
  "Video Production",
  "Public Speaking",
  "Machine Learning",
  "Disaster Response",
  "Cardiology",
  "Astronomy",
  "Oceanography",
  "Fitness Training",
  "Neurology",
  "Homebrewing",
  "Quantum Computing",
  "Sculpture",
  "Video Games",
  "Fishing",
  "Sociology",
  "Psychology",
  "Transportation",
  "Gardening",
  "History",
  "Navigation",
  "Natural Language Processing",
  "Cryptography",
  "Nanotechnology",
  "Recycling",
  "Anthropology",
  "Botany",
  "Blockchain",
];

export default async function handler(req, res) {
  console.log("GET AREAS");
  if (req.method === "GET") {
    return res.send({ areas });
    // const response = await fetch(
    //   "https://jsonplaceholder.typicode.com/todos/1"
    // );
    // res.send(response);
    // Process a POST request
  } else {
    return res.sendStatus(500);
    // Handle any other HTTP method
  }
}
